apiVersion: kubesphere.io/v1alpha1
name: fluid
version: 0.1.0
displayName:
  zh: fluid
  en: fluid
description:
  zh: Fluid是一个开源的Kubernetes原生的分布式数据集编排和加速引擎，主要服务于云原生场景下的数据密集型应用，例如大数据应用、AI应用等。
  en: Fluid is an open - source Kubernetes - native distributed dataset orchestration and acceleration engine, mainly serving data - intensive applications in cloud - native scenarios, such as big data applications, AI applications, etc.
category: storage
keywords:
  - storage
home: https://fluid-cloudnative.github.io/
sources:
  - https://github.com/fluid-cloudnative/fluid
kubeVersion: ">=1.19.0-0"
ksVersion: ">=4.0.0-0"
maintainers:
  - name: "fluid"
    email: ""
    url: ""
provider:
  zh:
    name: "fluid"
    email: ""
    url: ""
  en:
    name: "fluid"
    email: ""
    url: ""
icon: ./static/favicon.svg
screenshots:
  - ./static/screenshots/screenshot.png
dependencies:
  - name: frontend
    tags:
    - extension
  - name: fluid
    tags:
    - agent
# installationMode describes how to install subcharts, it can be HostOnly or Multicluster.
# In Multicluster mode, the subchart with tag `extension` will only be deployed to the host cluster,
# and the subchart with tag `agent` will be deployed to all selected clusters.
installationMode: Multicluster
# Custom namespace example: If not specified, it will be installed in the namespace named extension-{name}.
#namespace: ""
# external dependencies example
#externalDependencies:
#  - name: a
#    type: extension
#    version: ">= 2.6.0"
#    required: true
#  - name: b
#    type: extension
#    version: ">= 2.2.0"
#    required: true
# Add init containers to the extension installation job to execute custom tasks (eg: CRDs upgrade).
# Support unified or separate configuration of init container image for each stage.
#annotations:
#  executor-hook-image.kubesphere.io: ...
#  executor-hook-image.kubesphere.io/install: ...
#  executor-hook-image.kubesphere.io/upgrade: ...
#  executor-hook-image.kubesphere.io/uninstall: ...
images:
  - docker.io/fluidcloudnative/csi-node-driver-registrar:v2.3.0
  - docker.io/fluidcloudnative/fluid-csi:v1.0.5-7e917c7
  - docker.io/fluidcloudnative/alluxioruntime-controller:v1.0.5-7e917c7
  - docker.io/fluidcloudnative/dataset-controller:v1.0.5-7e917c7
  - docker.io/fluidcloudnative/efcruntime-controller:v1.0.5-7e917c7
  - docker.io/fluidcloudnative/application-controller:v1.0.5-7e917c7
  - docker.io/fluidcloudnative/goosefsruntime-controller:v1.0.5-7e917c7
  - docker.io/fluidcloudnative/jindoruntime-controller:v1.0.5-7e917c7
  - docker.io/fluidcloudnative/juicefsruntime-controller:v1.0.5-7e917c7
  - docker.io/fluidcloudnative/thinruntime-controller:v1.0.5-7e917c7
  - docker.io/fluidcloudnative/vineyardruntime-controller:v1.0.5-7e917c7
  - docker.io/fluidcloudnative/fluid-webhook:v1.0.5-7e917c7
  - docker.io/fluidcloudnative/fluid-crd-upgrader:v1.0.5-7e917c7
  - docker.io/fluidcloudnative/init-users:v0.9.0
  - docker.io/juicedata/mount:ce-v1.2.0
  - docker.io/juicedata/mount:ee-5.0.21-317356c
  - docker.io/alluxio/alluxio-dev:2.9.0
  - registry.cn-shanghai.aliyuncs.com/jindofs/smartdata:6.2.0
  - registry.cn-shanghai.aliyuncs.com/jindofs/jindo-fuse:6.2.0
  - registry.cn-zhangjiakou.aliyuncs.com/nascache/init-alifuse:v1.2.2-19dcee9
  - registry.cn-zhangjiakou.aliyuncs.com/nascache/efc-master:v1.2.2-19dcee9
  - registry.cn-zhangjiakou.aliyuncs.com/nascache/efc-worker:v1.2.2-19dcee9
  - registry.cn-zhangjiakou.aliyuncs.com/nascache/efc-fuse:v1.2.2-19dcee9
  - registry.aliyuncs.com/vineyard/vineyardd:v0.22.2
  - registry.aliyuncs.com/vineyard/vineyard-fluid-fuse:v0.22.2
  - ccr.ccs.tencentyun.com/qcloud/goosefs:v1.2.0
  - ccr.ccs.tencentyun.com/qcloud/goosefs-fuse:v1.2.0
